# Database
DROP DATABASE IF EXISTS recyco;
CREATE DATABASE IF NOT EXISTS recyco;
USE recyco;

# Tables
CREATE TABLE IF NOT EXISTS users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_login_at TIMESTAMP NULL,
	total_score INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS scores(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	points INT NOT NULL,
	correct_items INT NOT NULL,
	total_items INT NOT NULL,
	duration_ms INT NOT NULL,
	played_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS badges(
	id INT AUTO_INCREMENT PRIMARY KEY,
	code VARCHAR(50) UNIQUE NOT NULL,
	label VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	threshold INT NULL,
	icon VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS user_badges(
	user_id INT NOT NULL,
	badge_id INT NOT NULL,
	awarded_at TIMESTAMP NOT NULL,
	PRIMARY KEY(user_id, badge_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_items(
	id INT AUTO_INCREMENT PRIMARY KEY,
	sku VARCHAR(100) NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL,
	price INT NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_inventory(
	user_id INT NOT NULL,
	item_id INT NOT NULL,
	acquired_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(user_id, item_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (item_id) REFERENCES shop_items(id) ON DELETE CASCADE
);
